name: Node.js Build and Deploy to Neocities

on:
 workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    # Safety net so something weird doesn't happen from multiple jobs running at once
    concurrency:
      group: build-and-deploy
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Collect deps and build
      run: |
        npm ci
        npm run build --if-present
    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v2
      with:
        api_token: ${{ secrets.NEOCITIES_API_KEY }}
        cleanup: true
        dist_dir: output
